### PR TITLE
misc linting cleanup

### PR DESCRIPTION
**Pull request by sulrich**
as noted on the tin.

@fredhsu i think we discussed this previously, but we should add a `markdownlint` check to pull requests.

### CODE REVIEW

**Review by ksator — COMMENTED** [review]
Hello 
I am OK with the proposed changed for these 3 files:   
- docs/examples/gnoi/gnoic/index.md 
- docs/examples/gnoi/grpcurl/index.md 
- docs/examples/pyang/index.md 

@burnyd could you please reveiw the change proposed for this file `docs/examples/ygot/index.md`? 

Thanks!

**Review by ksator — CHANGES_REQUESTED** [review]
Hello, 

in ```docs/examples/ygot/index.md``` file  

```[openconfig-system model](https://github.com/openconfig/public/blob/master/release/models/system/.openconfig-system.yang)```
should be 
```[openconfig-system model](https://github.com/openconfig/public/blob/master/release/models/system/openconfig-system.yang)```

**Comment by ksator** [comment]
except that broken link, this PR LGTM

**Comment by sulrich** [comment]
URL fixed, minor formatting, etc edits as well.

**Review by ksator — APPROVED** [review]
LGTM!

**Pull request merged**
