### PR TITLE
initial notes re: style guide

### PR DESCRIPTION
**Pull request by sulrich**
NB - this is a draft for discussion

- addresses 
  - #57 
  - #60 

there's some opinion expressed here.  comments appreciated.

### CODE REVIEW

**Comment by ksator** [comment]
Hello, I think this is a very good idea to: 
- add a  TOC in the README file. 
- move all the contributions guide, style  guide ... from the README to a separate md so the README will be more about presenting the content of the repo

**Comment by sulrich** [comment]
very useful!  i think i see what you’re going for here now. i think we can dust this up accordingly

**Comment by ksator** [comment]
cool! 
Thanks! Could we please also include the `contributing.md` in the `mkdocs.yml` as well (in add to include a link to the `contributing.md` in the README.md file). 
Same if we create other md files (external reference, about,  deployment guide, installation, ...).

**Review by fredhsu — APPROVED** [review]
lgtm

**Pull request merged**
